language: python

language: python
python:
  - "3.5"
  - "2.7"
install: "pip install -r requirements.txt"
script: coverage run -m unittest discover && coverage report
after_success:
  - coveralls

env:
  - DB=postgres

before_script:
  - psql -c "CREATE DATABASE hello_books_test;" -U postgres
