language: python
python:
  - "3.6"

postgres:
  adapter: postgresql
  database: hello_books_test

services:
  - postgresql
before-script:
  - psql -c 'create database hello_books_test;' -U postgres
install: "pip install -r requirements.txt"
script: coverage run -m unittest discover && coverage report
after_success:
  - coveralls
