language: python
python:
  - "3.6"

postgres:
  adapter: postgresql
  database: test_db

services:
  - postgresql
before-script:
  - psql -c 'create database test_db;' -U postgres
install: "pip install -r requirements.txt"
script: coverage run -m unittest discover && coverage report
after_success:
  - coveralls

env:
 - DB=postgres

before_script:
 - psql -c "CREATE DATABASE hello_book;" -U postgres
