"""empty message

Revision ID: 1b54b1fddbdc
Revises: 
Create Date: 2018-06-11 18:53:09.095777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b54b1fddbdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow',
    sa.Column('borrow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('date_borrowed', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('borrow_id')
    )
    op.drop_table('borrows')
    op.drop_table('blacklisted_tokens')
    op.add_column('books', sa.Column('city_published', sa.String(), nullable=True))
    op.add_column('books', sa.Column('edition', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('isnb', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'isnb')
    op.drop_column('books', 'edition')
    op.drop_column('books', 'city_published')
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blacklisted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='blacklisted_tokens_pkey')
    )
    op.create_table('borrows',
    sa.Column('borrow_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_borrowed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('return_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('returned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='borrows_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='borrows_user_id_fkey'),
    sa.PrimaryKeyConstraint('borrow_id', name='borrows_pkey')
    )
    op.drop_table('borrow')
    # ### end Alembic commands ###
